### ISSUE TITLE
`None` values from BatteryPool's SoC/Capacity methods

### ISSUE THREAD

**Issue by shsms** [frequenz-floss/frequenz-sdk-python#545]
When a BatteryPool has no usable batteries,  it sends out a `None` value for `SoC`, `Capacity` and `PowerBounds`,  indicating that these values are not available, in the absence of working batteries.

We need to figure out how this information can be more clearly represented.

One option is in the case of `SoC` and `Capacity`, which stream `Sample` objects,  we can just set the `Sample`s value to `None` instead.  And provide a similar mechanism for the `PowerBounds` as well.

**Comment by thomas-nicolai-frequenz** [comment]
> We need to figure out how this information can be more clearly represented.

I suggest to make this `0` instead of `None`. `None` should be reserved for the case if something is broken and because of that there can't be anything reported. If there is no battery available reporting should be 0 imho. If could also be very well that we have all readings and still we can't use any battery (e.g. temperature).

**Comment by shsms** [comment]
@thomas-nicolai-frequenz I would like to understand the difference between "something is broken" vs "no battery available".  By the latter, do you mean that the battery ids mentioned are not part of the component graph?

For some types of errors, we get notified from the microgrid API,  but if a battery or an inverter crashes,  we just stop receiving data.  I'd think that classifies as "broken" as well.

In that case,  what does "no battery available" mean?

**Comment by thomas-nicolai-frequenz** [comment]
@sahas-subramanian-frequenz I see your point. Its even more tricky when talking about a pool, a set of batteries. Some are offline (no network connectivity/BMS crashed) and some have a SoP of 0. I general I would use the example of the SoP being zero because all batteries are overheated vs. SoP not available because the switch that connects to the batteries is gone and there is no network connectivity. Does that distinction make sense?

**Comment by thomas-nicolai-frequenz** [comment]
^about the above. That means as long as one battery of a given pool has an SoP >=0 the BatteryPool will also report an SoP >= 0. Only in case all batteries in a given pool are not available we would report None. Does that make sense?

**Comment by shsms** [comment]
> That means as long as one battery of a given pool has an SoP >=0 the BatteryPool will also report an SoP >= 0. Only in case all batteries in a given pool are not available we would report None. Does that make sense?

yup,  and that's how it is already.

I think in that case, the only improvement we can make is that we send a `Sample(None)` instead of just `None`, because then we won't have two levels of optional for users to deal with.

I think for before 1.0 still,  because that would be a breaking change.

**Comment by thomas-nicolai-frequenz** [comment]
> I think for before 1.0 still, because that would be a breaking change.

agreed. Its already assigned to 0.25
