### ISSUE TITLE
[Documentation] `ComponentMetricId` is not documented

### ISSUE THREAD

**Issue by matthias-wende-frequenz** [frequenz-floss/frequenz-sdk-python#985]
### What happened?

The `ComponentMetricId` is used as a type for parameters in several places in the Documentation but the Type itself is not documented, which makes it hard to determine what to pass.

### What did you expect instead?

Link to the documentation or definition.

### Affected part(s)

Documentation (part:docs)

### Extra information

This is the link to the definition.
https://github.com/frequenz-floss/frequenz-client-microgrid-python/blob/v0.x.x/src/frequenz/client/microgrid/_component.py#L192

**Comment by llucax** [comment]
So the class is documented, it is just not publicly exposed, right? So this issue is only about re-exporting it in https://github.com/frequenz-floss/frequenz-client-microgrid-python/blob/v0.x.x/src/frequenz/client/microgrid/__init__.py, right? Or do you think the class documentation needs to be improved too?

**Comment by matthias-wende-frequenz** [comment]
It's about exposing it publicly.

**Comment by llucax** [comment]
Easy fix then.
