### ISSUE TITLE
Add support for standardized logging

### ISSUE THREAD

**Issue by cwasicki** [frequenz-floss/frequenz-sdk-python#997]
### What's needed?

We discussed to add support to the SDK to have a standardized way for logging in python actors. 

### Proposed solution

@llucax proposed to support fine-grained logging configs via the `logging.config` package.

### Use cases

The goal is to have a common way to set log levels on a per actor basis via the config files.

**Comment by llucax** [comment]
TIL we can use the new `format()`-style placeholders in logging, it just needs some extra config:

https://docs.python.org/3/howto/logging-cookbook.html#formatting-styles

I'm not sure if this is really an option or not, because it will probably break any third-party library (and maybe even linters, that usually interpret logging strings specially), but something we might want to look into.
